project_id = "tu-project-id"

[functions.course-enrollment]
verify_jwt = true

[functions.lesson-progress]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true